type Query {
    stations: [ChargingStation!]!
    station(id: ID!): ChargingStation
    stationConnectors(stationId: ID!): [StationConnector!]!
}

type Mutation {
    registerStation(input: RegisterStationInput!): ChargingStation!
}

type ChargingStation {
    id: ID!
    name: String!
    status: StationStatus!
}

type StationConnector {
    evseId: Int!
    connectorId: Int!
    status: ConnectorStatus!
    statusUpdatedAt: String!
}

input RegisterStationInput {
    id: ID!
    name: String!
}

enum StationStatus {
    ONLINE
    OFFLINE
}

enum ConnectorStatus {
    AVAILABLE
    OCCUPIED
    RESERVED
    UNAVAILABLE
    FAULTED
}