spring.application.name=operations-service

server.port=${SERVER_PORT:8081}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP:operations-service}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

voltgrid.kafka.station-status-topic=voltgrid.station-status-changed.v1

spring.datasource.url=${OPERATIONS_DB_URL:jdbc:postgresql://localhost:5436/voltgrid_operations}
spring.datasource.username=${OPERATIONS_DB_USER:voltgrid}
spring.datasource.password=${OPERATIONS_DB_PASSWORD:voltgrid_dev}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

voltgrid.kafka.station-status-dlt-topic=voltgrid.station-status-changed.v1.dlt
voltgrid.kafka.consumer.retry-backoff-ms=500
voltgrid.kafka.consumer.max-retries=2

spring.kafka.listener.ack-mode=record

management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true
management.endpoint.health.probes.add-additional-paths=true
management.endpoint.health.group.readiness.include=readinessState,db

management.opentelemetry.tracing.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:http://localhost:4318/v1/traces}
management.tracing.sampling.probability=${TRACING_SAMPLING_PROBABILITY:1.0}